[project]
name = "personal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.5.1",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.43.2",
]
